# App config
server:
  servlet:
    context-path: /api-bff
  port: 0

# JSON serialization config
spring:
  application:
    name: apibff

  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html