# Spring config
server:
  servlet:
    context-path: /api-bff
  port: 5050

# JSON serialization config
spring:
  jackson:
    default-property-inclusion: non_null


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html