openapi: 3.0.0
info:
  title: api--bff API
  description: BFF API.
  version: 0.1.9
servers:
  - url: http://localhost:5000/v1
    description: Optional server description, e.g. Main (production) server
paths:
  /stocks:
    get:
      operationId: getStocks
      summary: Returns a list of stocks.
      responses:
        '200':    # status code
          description: A JSON array of stocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stock'
components:
  schemas:
    Stock:
      type: object
      required:
        - id
        - code
        - companyCnpj
        - companyName
        - holderCompanyCnpj
        - holderCompanyName
        - stockType
      properties:
        id:
          type: integer
          format: int32
        code:
          type: string
        companyCnpj:
          type: string
        companyName:
          type: string
        holderCompanyCnpj:
          type: string
        holderCompanyName:
          type: string
        stockType:
          type: integer
          format: int32
