openapi: 3.0.0
info:
  title: api-bff API
  description: BFF API.
  version: 0.1.9
servers:
  - url: http://localhost:0
    description: Optional server description, e.g. Main (production) server
paths:
  /stocks:
    get:
      summary: Returns a list of stocks.
      operationId: getStocks
      responses:
        '200':    # status code
          description: A JSON array of stocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stock'
    post:
      summary: Save stock data.
      operationId: saveStock
      responses:
        '201': # status code
          description: Create a new record for a stock
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stock'
  /stocks/{id}:
    get:
      summary: Returns a stock by the Id.
      operationId: getStockById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200': # status code
          description: A JSON object of a stock
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
  /brokers:
    get:
      summary: Returns a list of stocks.
      operationId: getBrokers
      responses:
        '200': # status code
          description: A JSON array of brokers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Broker'
    post:
      summary: Save stock data.
      operationId: saveBroker
      responses:
        '201': # status code
          description: Create a new record for a broker
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Broker'
  /brokers/{id}:
    get:
      summary: Returns a broker by the Id.
      operationId: getBrokerById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200': # status code
          description: A JSON object of a broker
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Broker'
components:
  schemas:
    Stock:
      type: object
      required:
        - code
        - companyCnpj
        - companyName
        - holderCompanyCnpj
        - holderCompanyName
        - stockType
      properties:
        id:
          type: integer
          format: int32
        code:
          type: string
        companyCnpj:
          type: string
        companyName:
          type: string
        holderCompanyCnpj:
          type: string
        holderCompanyName:
          type: string
        stockType:
          type: integer
          format: int32
    Broker:
      type: object
      required:
        - brokerShortName
        - brokerName
        - brokerCnpj
      properties:
        id:
          type: integer
          format: int32
        brokerShortName:
          type: string
        brokerName:
          type: string
        brokerCnpj:
          type: string
