openapi: 3.0.0
info:
  title: api--bff API
  description: BFF API.
  version: 0.1.9
servers:
  - url: http://localhost:5050/api-bff
    description: Optional server description, e.g. Main (production) server
paths:
  /stocks:
    get:
      summary: Returns a list of stocks.
      operationId: getStocks
      responses:
        '200':    # status code
          description: A JSON array of stocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stock'
    post:
      summary: Save stock data.
      operationId: saveStock
      responses:
        '201': # status code
          description: Create a new record for a stock
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stock'
  /stocks/{id}:
    get:
      summary: Returns a stock by the Id.
      operationId: getStockById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200': # status code
          description: A JSON object of a stock
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stock'
components:
  schemas:
    Stock:
      type: object
      required:
        - id
        - code
        - companyCnpj
        - companyName
        - holderCompanyCnpj
        - holderCompanyName
        - stockType
      properties:
        id:
          type: integer
          format: int32
        code:
          type: string
        companyCnpj:
          type: string
        companyName:
          type: string
        holderCompanyCnpj:
          type: string
        holderCompanyName:
          type: string
        stockType:
          type: integer
          format: int32
