version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack-full 
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
     - "localstack-vol:/tmp/localstack" #use a volume not a path
  
  mysql_db:
    image: mysql:latest
    container_name: mysql_localstack
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql       

  jaeger:
    container_name: jaeger_localstack
    image: jaegertracing/all-in-one    
    depends_on:
      - "localstack"
    ports:
      - "14268:14268"
volumes:
  my-db:
  localstack-vol: 
    
    
