services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=fakeAccessKeyId
      - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
      - REGION=us-east-1
      - DEBUG=${DEBUG-}
      - PERSISTENCE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DNS_ADDRESS=0
    volumes:
     - /home/goncalvesdiogo/work/gitRepo/Portifolio-Dev/docker/volume/localstack:/var/lib/localstack
     - ./scripts:/etc/localstack/init/ready.d
     - /var/run/docker.sock:/var/run/docker.soc
  
  mysql_db:
    image: mysql:8.0.36
    container_name: mysql_localstack
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /home/goncalvesdiogo/work/gitRepo/Portifolio-Dev/docker/volume/mysql:/var/lib64/mysql

  jaeger:
    container_name: jaeger_localstack
    image: jaegertracing/all-in-one:1.58    
    depends_on:
      - "localstack"
    ports:
      - "14268:14268"
volumes:
  my-db:
  localstack-vol: 
    
    
