# App config
server:
  servlet:
    context-path: /service-stock
  port: 0

# Spring config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_stocks_db?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${db_username}
    password: ${db_password}

    #url: jdbc-secretsmanager:mysql://localhost:3306/my_stocks_db?createDatabaseIfNotExist=true
    #driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    #user: /secret/servicestock
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

  # JSON config
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Flyway config
flyway:
  url: ${spring.datasource.url}
  schema: my_stocks_db
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}




# swagger-ui config
springdoc:
  swagger-ui:
    path: /swagger-ui.html

#logging:
#  level:
#    root: DEBUG
